spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/account

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
